/**
 * Prompt Evolver — manages and evolves LLM prompt variants
 * for planner, replanner, and diagnoser roles.
 *
 * Maintains a population of prompt variants with Beta beliefs.
 * Uses Thompson Sampling to select which variant to use.
 * After each run, updates the selected variant's belief.
 *
 * Based on: Darwin Godel Machine (Sakana AI, 2025) evolutionary selection.
 */

import type { PromptVariant, BetaBelief } from "../cognition/types";
import { sampleBeta, betaMean } from "../cognition/types";
import { logModuleError } from "../core/module-logger";

// In-memory prompt variant store
const variants: Map<string, PromptVariant[]> = new Map();

/**
 * Register a base prompt variant for a role.
 */
export function registerBasePrompt(
  role: PromptVariant["role"],
  systemPrompt: string
): PromptVariant {
  const variant: PromptVariant = {
    id: `prompt-${role}-base`,
    role,
    systemPrompt,
    successCount: 0,
    failureCount: 0,
    belief: { alpha: 2, beta: 1 },  // slight optimistic prior for base
    createdAt: new Date().toISOString()
  };

  const existing = variants.get(role) ?? [];
  // Don't duplicate base
  if (!existing.some(v => v.id === variant.id)) {
    existing.push(variant);
  }
  variants.set(role, existing);
  return variant;
}

/**
 * Add a new prompt variant (e.g., generated by LLM mutation).
 */
export function addVariant(
  role: PromptVariant["role"],
  systemPrompt: string,
  parentId?: string
): PromptVariant {
  const variant: PromptVariant = {
    id: `prompt-${role}-${Date.now().toString(36)}`,
    role,
    systemPrompt,
    successCount: 0,
    failureCount: 0,
    belief: { alpha: 1, beta: 1 },  // uninformative prior for new variant
    createdAt: new Date().toISOString()
  };

  const existing = variants.get(role) ?? [];
  existing.push(variant);
  variants.set(role, existing);
  return variant;
}

/**
 * Select a prompt variant for a role using Thompson Sampling.
 */
export function selectPrompt(role: PromptVariant["role"]): PromptVariant | null {
  const pool = variants.get(role);
  if (!pool || pool.length === 0) return null;

  let best: PromptVariant | null = null;
  let bestScore = -1;

  for (const variant of pool) {
    const score = sampleBeta(variant.belief);
    if (score > bestScore) {
      bestScore = score;
      best = variant;
    }
  }

  return best;
}

/**
 * Record outcome for a prompt variant.
 */
export function recordPromptOutcome(variantId: string, success: boolean): void {
  for (const pool of variants.values()) {
    const variant = pool.find(v => v.id === variantId);
    if (variant) {
      if (success) {
        variant.successCount += 1;
        variant.belief.alpha += 1;
      } else {
        variant.failureCount += 1;
        variant.belief.beta += 1;
      }
      break;
    }
  }
}

/**
 * Get the best-performing variant for a role (by posterior mean).
 */
export function getBestVariant(role: PromptVariant["role"]): PromptVariant | null {
  const pool = variants.get(role);
  if (!pool || pool.length === 0) return null;

  return pool.reduce((best, v) =>
    betaMean(v.belief) > betaMean(best.belief) ? v : best
  );
}

/**
 * Prune underperforming variants (keep top N by posterior mean).
 */
export function pruneVariants(role: PromptVariant["role"], keepTop: number = 5): number {
  const pool = variants.get(role);
  if (!pool || pool.length <= keepTop) return 0;

  pool.sort((a, b) => betaMean(b.belief) - betaMean(a.belief));
  const removed = pool.length - keepTop;
  pool.length = keepTop;
  return removed;
}

export function getVariants(role: PromptVariant["role"]): PromptVariant[] {
  return [...(variants.get(role) ?? [])];
}

export function getAllVariants(): Record<string, PromptVariant[]> {
  const result: Record<string, PromptVariant[]> = {};
  for (const [role, pool] of variants) {
    result[role] = [...pool];
  }
  return result;
}

export function restoreVariants(data: Record<string, PromptVariant[]>): void {
  variants.clear();
  for (const [role, pool] of Object.entries(data)) {
    variants.set(role, pool);
  }
}

export function resetVariants(): void {
  variants.clear();
}

/**
 * Generate a new prompt variant by asking an LLM to improve the worst-performing variant.
 * Called at the end of each run to evolve the prompt pool.
 */
export async function mutatePrompt(role: PromptVariant["role"]): Promise<PromptVariant | null> {
  // Find worst variant (lowest success rate with at least 3 attempts)
  const pool = variants.get(role) ?? [];
  const candidates = pool.filter(v => (v.successCount + v.failureCount) >= 3);
  if (candidates.length === 0) return null;

  candidates.sort((a, b) => betaMean(a.belief) - betaMean(b.belief));
  const worst = candidates[0];
  const best = pool.reduce((a, b) => betaMean(a.belief) > betaMean(b.belief) ? a : b);

  try {
    const { readProviderConfig, callOpenAICompatible, callAnthropic } = require("../llm/provider");
    const config = readProviderConfig("LLM_PLANNER", { maxTokens: 600 });
    if (!config.apiKey) return null;

    const messages = [
      { role: "system" as const, content: "You are a prompt engineer. Given a poorly performing system prompt and a well performing one, create an improved version. Return ONLY the new prompt text, nothing else." },
      { role: "user" as const, content: `Poorly performing prompt (success rate: ${(worst.successCount / Math.max(1, worst.successCount + worst.failureCount) * 100).toFixed(0)}%):\n${worst.systemPrompt}\n\nBest performing prompt (success rate: ${(best.successCount / Math.max(1, best.successCount + best.failureCount) * 100).toFixed(0)}%):\n${best.systemPrompt}\n\nCreate an improved version that combines the strengths of the best with fixes for the worst's weaknesses.` }
    ];

    const callLLM = config.provider === "anthropic" ? callAnthropic : callOpenAICompatible;
    const result = await callLLM(config, messages, "PromptEvolver");

    if (result.content && result.content.length > 20) {
      return addVariant(role, result.content, worst.id);
    }
  } catch (error) {
    logModuleError("prompt-evolver", "optional", error, "LLM prompt mutation failed");
  }
  return null;
}
