/**
 * PDF Report Export — generates professional PDF from investigation data
 * Uses HTML→PDF via Playwright (no external dependencies)
 */

export interface PdfExportOptions {
  title?: string;
  includeRawData?: boolean;
  logo?: string;
}

export async function generatePdfReport(
  report: { markdown: string; title: string; riskLevel: string; timestamp: string },
  options: PdfExportOptions = {}
): Promise<Buffer> {
  const html = buildReportHtml(report, options);

  try {
    const { chromium } = await import("playwright");
    const browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
      printBackground: true,
    });
    await browser.close();
    return Buffer.from(pdf);
  } catch {
    // Fallback: return HTML as buffer if Playwright unavailable
    return Buffer.from(html, "utf-8");
  }
}

function buildReportHtml(
  report: { markdown: string; title: string; riskLevel: string; timestamp: string },
  options: PdfExportOptions
): string {
  const riskColors: Record<string, string> = {
    critical: "#ef4444", high: "#f97316", medium: "#f59e0b", low: "#22c55e",
  };
  const riskColor = riskColors[report.riskLevel] || "#64748b";

  // Convert markdown to simple HTML
  const bodyHtml = markdownToHtml(report.markdown);

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1e293b; line-height: 1.6; font-size: 11px; }
  .header { background: #0f172a; color: #e2e8f0; padding: 24px 32px; margin: -20mm -15mm 24px; }
  .header h1 { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
  .header .meta { font-size: 10px; color: #94a3b8; }
  .risk-badge { display: inline-block; padding: 3px 12px; border-radius: 12px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: white; background: ${riskColor}; }
  h2 { font-size: 14px; font-weight: 700; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; margin: 20px 0 10px; }
  h3 { font-size: 12px; font-weight: 600; color: #334155; margin: 14px 0 6px; }
  p { margin: 6px 0; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 10px; }
  th, td { border: 1px solid #e2e8f0; padding: 4px 8px; text-align: left; }
  th { background: #f8fafc; font-weight: 600; color: #475569; }
  ul, ol { margin: 6px 0; padding-left: 20px; }
  li { margin: 2px 0; }
  code { background: #f1f5f9; padding: 1px 4px; border-radius: 2px; font-size: 10px; font-family: monospace; }
  pre { background: #0f172a; color: #22c55e; padding: 10px; border-radius: 4px; overflow-x: auto; font-size: 9px; margin: 8px 0; }
  .footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; text-align: center; }
  strong { font-weight: 600; }
  @media print { .header { margin: 0; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(options.title || report.title)}</h1>
    <div class="meta">
      <span>Date: ${new Date(report.timestamp).toLocaleDateString()} ${new Date(report.timestamp).toLocaleTimeString()}</span>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      Risk Level: <span class="risk-badge">${report.riskLevel}</span>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      Generated by Panopticon
    </div>
  </div>
  ${bodyHtml}
  <div class="footer">
    This report was automatically generated by Panopticon — AI-powered open-source intelligence platform.<br>
    Confidential — handle according to your organization's information classification policy.
  </div>
</body>
</html>`;
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^\| (.+) \|$/gm, (_, row) => {
      const cells = row.split("|").map((c: string) => c.trim());
      return `<tr>${cells.map((c: string) => `<td>${c}</td>`).join("")}</tr>`;
    })
    .replace(/^\|[-|]+\|$/gm, "")
    .replace(/(<tr>[\s\S]*?<\/tr>\n?)+/g, (table) => `<table>${table}</table>`)
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>[\s\S]*?<\/li>\n?)+/g, (list) => `<ul>${list}</ul>`)
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    .replace(/^(?!<[a-z])([\s\S]+?)$/gm, (_, text) => text.trim() ? `<p>${text.trim()}</p>` : "")
    .replace(/---/g, "<hr>");
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
